function saveFig(fig, file, height, width, varargin)
%SAVEFIG Saves a figure
cleanfigure('handle', fig, 'scalePrecision', 0)
matlab2tikz(fullfile('figs', file),            ...
    'figurehandle', fig,     ...
    'showInfo', false,       ...
    'parseStrings', false,   ...
    'extraTikzpictureOptions','trim axis left',       ...
    'extraAxisOptions', 'legend style={font=\small}', ...
    'height', height, 'width', width, varargin{:})
end
